name: app_monitor
description: "App monitoring lib for logging and error handling."
version: 1.0.0
homepage: https://github.com/feridhub/app_monitor

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.6
  test_cov_console: ^0.2.2

flutter: